sudo: false
language: node_js
node_js:
  - "iojs-v2.1.0"
notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/006ca15725d53eab80e5
    on_success: always
    on_failure: always
    on_start: false
before_install:
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
