language: node_js
node_js:
  - node

jobs:
  include:
    - stage: Chrome
      addons:
        chrome: stable
      env: BROWSER=ChromeCi
    - stage: Firefox
      addons:
        firefox: latest
      env: BROWSER=Firefox

services:
  - xvfb

cache:
  yarn: true
  npm: true
  directories:
    - www/node_modules

before_install:
  - export DISPLAY=:99.0

install:
  - yarn bootstrap

after_success:
  - node_modules/.bin/codecov

branches:
  only:
    - master
    - next
