language: node_js
node_js:
  - node

cache:
  yarn: true
  npm: true
  directories:
    - www/node_modules

jobs:
  include:
    - stage: Chrome
      env: BROWSER=ChromeCi
      addons:
        chrome: stable
    - stage: Firefox
      env: BROWSER=Firefox
      addons:
        firefox: latest

services:
  - xvfb

before_install:
  - export DISPLAY=:99.0

install:
  - yarn bootstrap

after_success:
  - node_modules/.bin/codecov

branches:
  only:
    - master
    - next
